spring:
  profiles:
    active: local
    include: 'blacklist'
  main.banner-mode: off

server:
  port: 8080
  forward-headers-strategy: native
  error.whitelabel.enabled: false

logging.level:
  org.springframework: INFO
  org.springframework.web: DEBUG
  com.underbell: DEBUG